### ISSUE TITLE
Will v6 work on devices that don't support "Mangle"?

### ISSUE THREAD

**Issue by MrEngineerMind** [felikcat/unlimited-hotspot#3]
I know a decent amount about android, but I am far from an expert.

But, from what I understand, the kernel of a device determines if "mangle" is supported for iptables.

Appraently, my kernel does not support Mangle (I think I remember getting an error when I first tried this module back in march), but your 3/12/23 v5 mod did in fact seem to work because my hotspot data usage never decremented after I installed it.

But, I wanted to know if this half-baked condition is ok to run full-time, or will it raise red flags with my cell company because all the changes in your script were not able to be fully implemented properly?

**Comment by felikcat** [comment]
Kernels that don't support mangling won't change anything, it's why I lazily don't check for errors there.

It's optional though, and I'm still working on methods to not require a custom kernel, but it's specific to each OS; I only have macOS supported currently, and a hunch that Windows is supported by default through GhosTCP.
